services:
  hubproxy:
    build: .
    container_name: hubproxy
    restart: always
    ports:
      - "15000:15000"
    environment:
      - VPN_PROXY=${VPN_PROXY-}
      - SERVER_PORT=15000
      - BLOB_CACHE_ENABLED=true
    volumes:
      - ./blob-cache:/app/blob-cache
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "2"
